name: Sync to ReadMe

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - run: echo ${{ github.head_ref }}    
    - uses: readmeio/github-readme-sync@1.0.3
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}' # DON'T MODIFY--Allows us to get the contents of your spec file
        readme-api-id: '5e66202d876c54002efa833d' # The engagement's endpoints definition
        api-file-path: '/rest_api/glia_api_test.json' # path to API spec file
        readme-api-key: '1rtOVaHN6Q40D04hOOtEbKdJ0ZxTDWJs' # ReadMe API key 
        readme-api-version: '${{ github.head_ref }}'

    - uses: readmeio/github-readme-sync@1.0.3
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}' # DON'T MODIFY--Allows us to get the contents of your spec file
        readme-api-id: '58456757397853576f4f4942' # The operator's endpoints definition
        api-file-path: '/rest_api/operators.yaml' # path to API spec file
        readme-api-key: '1rtOVaHN6Q40D04hOOtEbKdJ0ZxTDWJs' # ReadMe API key 
        readme-api-version: '${{ github.head_ref }}' # ReadMe version to sync to

